[project]
name = 'On-Chain-Registry-and-Marketplace-for-Biodiversity-Credits'
description = ''
authors = []
telemetry = false
cache_dir = '.\.cache'
requirements = []
[contracts.marketplace]
path = 'contracts/marketplace.clar'
clarity_version = 3
epoch = 'latest'

[contracts.registry]
path = 'contracts/registry.clar'
clarity_version = 3
epoch = '3.2'

[contracts.verification]
path = 'contracts/verification.clar'
clarity_version = 3
epoch = 'latest'

[contracts.retirement]
path = 'contracts/retirement.clar'
clarity_version = 3
epoch = 'latest'

[contracts.staking]
path = 'contracts/staking.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
